/**
 * Machine-readable codes from the architecture specification.
 * Every failed validation path maps to exactly one of these strings.
 */

export const ORDER_SPLITTER_ERROR_CODES = {
  INVALID_WEIGHTS: 'INVALID_WEIGHTS',
  EMPTY_PORTFOLIO: 'EMPTY_PORTFOLIO',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_WEIGHT_VALUE: 'INVALID_WEIGHT_VALUE',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_ORDER_TYPE: 'INVALID_ORDER_TYPE',
  INVALID_PRECISION: 'INVALID_PRECISION',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  MALFORMED_REQUEST: 'MALFORMED_REQUEST',
  /** `stocks.length` exceeds `MAX_STOCKS_PER_ORDER` in `order-splitter/constants.ts`. */
  PORTFOLIO_TOO_LARGE: 'PORTFOLIO_TOO_LARGE',
} as const;

export type OrderSplitterErrorCode =
  (typeof ORDER_SPLITTER_ERROR_CODES)[keyof typeof ORDER_SPLITTER_ERROR_CODES];

/** All catalog codes — useful for exhaustive tests and tooling. */
export const ALL_ORDER_SPLITTER_ERROR_CODES: readonly OrderSplitterErrorCode[] = [
  ORDER_SPLITTER_ERROR_CODES.INVALID_WEIGHTS,
  ORDER_SPLITTER_ERROR_CODES.EMPTY_PORTFOLIO,
  ORDER_SPLITTER_ERROR_CODES.INVALID_AMOUNT,
  ORDER_SPLITTER_ERROR_CODES.INVALID_WEIGHT_VALUE,
  ORDER_SPLITTER_ERROR_CODES.INVALID_PRICE,
  ORDER_SPLITTER_ERROR_CODES.INVALID_ORDER_TYPE,
  ORDER_SPLITTER_ERROR_CODES.INVALID_PRECISION,
  ORDER_SPLITTER_ERROR_CODES.ORDER_NOT_FOUND,
  ORDER_SPLITTER_ERROR_CODES.MALFORMED_REQUEST,
  ORDER_SPLITTER_ERROR_CODES.PORTFOLIO_TOO_LARGE,
];
